server:
  port: 5601
  host: "0.0.0.0"
elasticsearch:
  url: "http://elasticsearch:9200"
  preserveHost: true
  ssl:
    verify: true
  requestTimeout: 300000
  shardTimeout: 0
kibana:
  index: ".kibana"
  defaultAppId: "discover"
